# Generated by Django 3.0.8 on 2020-07-24 12:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
