# Generated by Django 3.0.8 on 2020-07-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education_position',
            field=models.CharField(blank=True, choices=[('first prepratory', 'first prepratory'), ('second prepratory', 'second prepratory'), ('third prepratory', 'third prepratory'), ('first secondary', 'first secondary'), ('second secondary', 'second secondary'), ('third secondary', 'third secondary')], max_length=100),
        ),
    ]
