# Generated by Django 3.0.8 on 2020-07-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200719_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_position',
            field=models.CharField(blank=True, choices=[('first prepratory', 'first prepratory'), ('second prepratory', 'second prepratory'), ('third prepratory', 'third prepratory'), ('first secondary', 'first secondary'), ('second secondary', 'second secondary'), ('third secondary', 'third secondary')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_imgs/'),
        ),
    ]
