# Generated by Django 3.0.8 on 2020-07-18 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0012_auto_20200718_0243'),
        ('accounts', '0004_auto_20200719_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='subclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subclass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_sub', to='class.Class')),
            ],
            options={
                'verbose_name': 'subclass',
                'verbose_name_plural': 'subclasses',
            },
        ),
    ]
