# Generated by Django 3.0.8 on 2020-07-18 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_subclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subclass',
        ),
    ]
