# Generated by Django 3.0.8 on 2020-07-15 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Center',
                'verbose_name_plural': 'Centers',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='day_one',
            field=models.CharField(choices=[('1', 'saturday'), ('2', 'sunday'), ('3', 'monday'), ('4', 'tuesday'), ('5', 'wednesday'), ('6', 'thursday'), ('7', 'friday')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='day_two',
            field=models.CharField(blank=True, choices=[('1', 'saturday'), ('2', 'sunday'), ('3', 'monday'), ('4', 'tuesday'), ('5', 'wednesday'), ('6', 'thursday'), ('7', 'friday')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='class',
            name='main_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='class.MainSubject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainsubject',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='class.Center'),
        ),
    ]
