# Generated by Django 3.0.8 on 2020-07-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_auto_20200715_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
