# Generated by Django 3.0.8 on 2020-07-16 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lessons_text', models.TextField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('url1', models.URLField(blank=True, null=True)),
                ('url2', models.URLField(blank=True, null=True)),
                ('url3', models.URLField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('main_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_chapter', to='class.Chapter')),
                ('main_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_class', to='class.Class')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
    ]
