# Generated by Django 3.0.8 on 2020-07-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0007_auto_20200716_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='vid1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='vid2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='vid3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
