# Generated by Django 3.0.8 on 2020-07-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0009_auto_20200717_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='tutor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
