# Generated by Django 3.0.8 on 2020-07-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0010_auto_20200717_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='tutor',
            field=models.CharField(blank=True, default='a teacher', max_length=100, null=True),
        ),
    ]
