# Generated by Django 3.0.8 on 2020-07-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0011_auto_20200717_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
