# Generated by Django 3.0.8 on 2020-07-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0012_auto_20200718_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='day_one',
            field=models.CharField(choices=[('saturday', 'saturday'), ('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday')], max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='day_two',
            field=models.CharField(blank=True, choices=[('saturday', 'saturday'), ('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday')], max_length=100, null=True),
        ),
    ]
