# Generated by Django 3.0.8 on 2020-07-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('class', '0014_auto_20200720_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='notes',
            field=models.ManyToManyField(to='notes.Note'),
        ),
    ]
