# Generated by Django 3.0.8 on 2020-07-24 12:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0015_lesson_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='more_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lessons_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
