# Generated by Django 3.0.8 on 2020-07-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0017_auto_20200724_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsubject',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
