# Generated by Django 3.0.8 on 2020-08-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20200805_0027'),
        ('class', '0019_remove_mainsubject_main_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='notes',
            field=models.ManyToManyField(blank=True, to='notes.Note'),
        ),
    ]
