# Generated by Django 3.0.8 on 2020-08-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0020_auto_20200807_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsubject',
            name='book',
            field=models.FileField(blank=True, null=True, upload_to='main_sub_books/'),
        ),
    ]
