# Generated by Django 3.0.8 on 2020-09-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0021_mainsubject_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='main_video',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/'),
        ),
    ]
