# Generated by Django 3.0.8 on 2021-02-04 14:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0025_auto_20200919_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lessons_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
